BEGIN;

USE `beezzy`;

DROP TABLE CATEGORY;

CREATE TABLE CATEGORY(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PARENT_ID INTEGER,
  SHOP_ID INTEGER,
  CONSTRAINT `fk_CATEGORY_parent_id` FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY(ID) ON DELETE NO ACTION,
  CONSTRAINT `fk_CATEGORY_shop_id` FOREIGN KEY (SHOP_ID) REFERENCES SHOP(ID) ON DELETE NO ACTION
);


COMMIT;